groups:
- name: lulLABy
  rules:

  # Alert for any photon that is unreachable for >5 minutes.
  # - alert: PhotonDown
  #   expr: up == 0
  #   for: 5m
  #   labels:
  #     severity: critical
  #   annotations:
  #     summary: "Photon {{ $labels.device_id }} down"
  #     description: "{{ $labels.device_id }} has been down for more than 5 minutes."

  # Alert for any instance that has a median request latency >1s.
  - alert: AmbientTemperatureOutOfRange
    expr: temperature_c{type="ambient"} > -22 or temperature_c{type="ambient"} < -30
    for: 1m
    annotations:
      summary: "Ambient temperature out of range on {{ $labels.device_id }}"
      description: "{{ $labels.device_id }} out of temperature range for 1 minute (current temperature: {{ $value }} C)"
